/* eslint-disable @next/next/no-img-element */
"use client";

import { useEffect, useMemo, useState } from "react";
import QRCode from "qrcode";
import { defaultStore, projects as defaultProjects } from "@/lib/data";
import type { StoreConfig } from "@/types/store";

type Stats={views:number;unique:number;starts:number;submits:number;generations:number;copies:number;publishes:number};
type GenerationRecord={id:string;createdAt:string;storeName:string;projectName:string;channelId:string;style:string;content:string};
type StoreForm={name:string;shortName:string;logoText:string;city:string;district:string;address:string;description:string;recommendedKeywords:string;forbiddenWords:string;defaultHashtags:string};
const emptyStats:Stats={views:0,unique:0,starts:0,submits:0,generations:0,copies:0,publishes:0};
const initialConfig:StoreConfig={store:defaultStore,projects:defaultProjects};
const tabs=["数据总览","门店设置","二维码管理","生成记录"] as const;
const toForm=(config:StoreConfig):StoreForm=>({...config.store,recommendedKeywords:config.store.recommendedKeywords.join("、"),forbiddenWords:config.store.forbiddenWords.join("、"),defaultHashtags:config.store.defaultHashtags.map((tag)=>`#${tag.replace(/^#/,"")}`).join(" ")});

export default function AdminPage(){
 const [authenticated,setAuthenticated]=useState<boolean|null>(null);const [username,setUsername]=useState("");const [password,setPassword]=useState("");const [message,setMessage]=useState("");const [stats,setStats]=useState(emptyStats);const [config,setConfig]=useState<StoreConfig>(initialConfig);const [tab,setTab]=useState<(typeof tabs)[number]>("数据总览");
 async function load(){const [summaryResponse,storeResponse]=await Promise.all([fetch("/api/admin/summary",{cache:"no-store"}),fetch("/api/admin/store",{cache:"no-store"})]);if(summaryResponse.status===401||storeResponse.status===401){setAuthenticated(false);return}if(!summaryResponse.ok||!storeResponse.ok)throw new Error("load_failed");const [summaryData,storeData]=await Promise.all([summaryResponse.json(),storeResponse.json()]);setStats(summaryData.stats);setConfig(storeData);setAuthenticated(true)}
 useEffect(()=>{let active=true;Promise.all([fetch("/api/admin/summary",{cache:"no-store"}),fetch("/api/admin/store",{cache:"no-store"})]).then(async([summaryResponse,storeResponse])=>({status:summaryResponse.status,storeStatus:storeResponse.status,summary:await summaryResponse.json(),config:await storeResponse.json()})).then((data)=>{if(!active)return;if(data.status===401||data.storeStatus===401){setAuthenticated(false);return}setStats(data.summary.stats);setConfig(data.config);setAuthenticated(true)}).catch(()=>{if(active)setAuthenticated(false)});return()=>{active=false}},[]);
 async function login(e:React.FormEvent){e.preventDefault();setMessage("");const response=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,password})});if(!response.ok){setMessage((await response.json()).message||"登录失败");return}setPassword("");await load()}
 async function logout(){await fetch("/api/admin/login",{method:"DELETE"});setAuthenticated(false)}
 if(authenticated===null)return <div className="admin-shell"><div className="loader-wrap"><div><div className="loader"/><p>正在打开管理后台……</p></div></div></div>;
 if(!authenticated)return <div className="mobile-shell"><div className="page no-dock"><div className="logo" style={{background:"var(--mint)",marginTop:40}}>{config.store.logoText}</div><h1 style={{marginTop:28}}>管理后台</h1><p className="sub">请输入管理员用户名和密码</p><form className="card section" onSubmit={login}><label className="field">管理员用户名<input className="input" autoComplete="username" value={username} maxLength={80} onChange={(e)=>setUsername(e.target.value)} placeholder="请输入用户名"/></label><label className="field">管理员密码<input className="input" type="password" autoComplete="current-password" value={password} maxLength={100} onChange={(e)=>setPassword(e.target.value)} placeholder="请输入密码"/></label>{message&&<div className="error">{message}</div>}<button className="btn btn-primary" style={{marginTop:16}} disabled={!username.trim()||!password}>登录</button></form><p className="fine-print section">本地演示账号见 .env.example，上线前请务必修改。</p></div></div>;
 return <div className="admin-shell"><div className="admin-inner"><header className="admin-header"><div><h1 style={{margin:0}}>种草助手管理台</h1><p className="sub">{config.store.name}</p></div><button type="button" className="btn btn-ghost" style={{width:"auto"}} onClick={logout}>退出登录</button></header><nav className="admin-tabs">{tabs.map(item=><button type="button" key={item} className={tab===item?"active":""} onClick={()=>setTab(item)}>{item}</button>)}</nav>{tab==="数据总览"&&<Overview stats={stats}/>} {tab==="门店设置"&&<StoreSettings config={config} onSaved={setConfig}/>} {tab==="二维码管理"&&<QrManager stats={stats} config={config}/>} {tab==="生成记录"&&<Records/>}</div></div>;
}

function Overview({stats}:{stats:Stats}){const cards=[["总访问次数",stats.views],["独立访问人数",stats.unique],["开始填写人数",stats.starts],["表单提交人数",stats.submits],["生成次数",stats.generations],["复制次数",stats.copies],["查看发布教程",stats.publishes],["访问→生成",stats.views?`${Math.round(stats.generations/stats.views*100)}%`:"0%"]];return <><div className="stats">{cards.map(([label,value])=><div className="stat" key={label}><span className="sub">{label}</span><strong>{value}</strong></div>)}</div><div className="card section"><h3>生成→复制转化率</h3><div className="progress-wrap" style={{height:12,marginTop:18}}><div className="progress" style={{width:`${stats.generations?Math.min(100,Math.round(stats.copies/stats.generations*100)):0}%`}}/></div><p className="sub">{stats.generations?Math.round(stats.copies/stats.generations*100):0}% · 统计仅包含必要的使用事件，不收集顾客姓名。</p></div></>}

function StoreSettings({config,onSaved}:{config:StoreConfig;onSaved:(config:StoreConfig)=>void}){
 const [form,setForm]=useState<StoreForm>(()=>toForm(config));const [projectNames,setProjectNames]=useState(config.projects.map((project)=>project.name).join("、"));const [status,setStatus]=useState("");const [saving,setSaving]=useState(false);
 const update=(key:keyof StoreForm,value:string)=>setForm((current)=>({...current,[key]:value}));
 async function save(){setSaving(true);setStatus("");try{const response=await fetch("/api/admin/store",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({store:form,projectNames})});const data=await response.json();if(!response.ok){setStatus(data.message||"保存失败，请稍后重试。");return}onSaved(data);setStatus("设置已保存，前台刷新后会读取最新配置。")}catch{setStatus("保存失败，请稍后重试。")}finally{setSaving(false)}}
 const basic:[[string,keyof StoreForm],...Array<[string,keyof StoreForm]>]=[["门店名称","name"],["门店简称","shortName"],["文字Logo","logoText"],["城市","city"],["商圈","district"],["门店地址","address"]];
 return <div className="admin-grid"><div className="card"><h2>基础信息</h2>{basic.map(([label,key])=><label className="field" key={key}>{label}<input className="input" value={form[key]} onChange={(event)=>update(key,event.target.value)}/></label>)}</div><div className="card"><h2>内容设置</h2><label className="field">门店介绍<textarea className="textarea" value={form.description} onChange={(event)=>update("description",event.target.value)}/></label><label className="field">服务项目<textarea className="textarea" value={projectNames} onChange={(event)=>setProjectNames(event.target.value)}/></label><label className="field">推荐关键词<input className="input" value={form.recommendedKeywords} onChange={(event)=>update("recommendedKeywords",event.target.value)}/></label><label className="field">禁用词<input className="input" value={form.forbiddenWords} onChange={(event)=>update("forbiddenWords",event.target.value)}/></label><label className="field">默认话题标签<input className="input" value={form.defaultHashtags} onChange={(event)=>update("defaultHashtags",event.target.value)}/></label><button type="button" className="btn btn-primary" style={{marginTop:16}} disabled={saving} onClick={save}>{saving?"保存中……":"保存设置"}</button>{status&&<p className={status.startsWith("设置已保存")?"":"error"} style={status.startsWith("设置已保存")?{color:"var(--green)"}:undefined}>{status}</p>}</div></div>
}

function QrManager({stats,config}:{stats:Stats;config:StoreConfig}){
 const [origin,setOrigin]=useState("");const [channel,setChannel]=useState("frontdesk");const [campaign,setCampaign]=useState("summer001");const [project,setProject]=useState("");const [qr,setQr]=useState("");
 useEffect(()=>{const timer=window.setTimeout(()=>setOrigin(window.location.origin),0);return()=>window.clearTimeout(timer)},[]);
 const url=useMemo(()=>{if(!origin)return "";const q=new URLSearchParams({storeId:config.store.id,campaignId:campaign,channelId:channel});if(project)q.set("projectId",project);return `${origin}/?${q}`},[origin,channel,campaign,project,config.store.id]);
 useEffect(()=>{if(!url)return;let active=true;QRCode.toDataURL(url,{width:440,margin:2,color:{dark:"#15352A",light:"#FFFFFF"}}).then((value)=>{if(active)setQr(value)});return()=>{active=false}},[url]);
 async function copy(){if(url)await navigator.clipboard.writeText(url)}
 return <div className="admin-grid"><div className="card"><h2>创建二维码</h2><label className="field">活动标识<input className="input" value={campaign} onChange={e=>setCampaign(e.target.value.replace(/[^a-zA-Z0-9_-]/g,"").slice(0,50))}/></label><label className="field">渠道<select className="input" value={channel} onChange={e=>setChannel(e.target.value)}><option value="frontdesk">前台</option><option value="cashier">收银台</option><option value="table">桌牌</option><option value="aftercare">服务结束区</option><option value="staff">员工专属</option></select></label><label className="field">预选体验项目<select className="input" value={project} onChange={e=>setProject(e.target.value)}><option value="">让顾客自己选择</option>{config.projects.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label className="field">二维码链接<textarea className="textarea" readOnly value={url}/></label><div className="split-actions"><button type="button" className="btn btn-secondary" onClick={copy}>复制链接</button><a className="btn btn-primary" style={{display:"grid",placeItems:"center"}} href={qr} download={`种草助手-${channel}.png`}>下载PNG</a></div></div><div className="card"><h2>在线预览</h2><div className="qr-preview">{qr&&<img src={qr} alt="当前渠道二维码"/>}</div><div className="stats" style={{gridTemplateColumns:"repeat(3,1fr)",marginTop:14}}><div className="stat"><span className="sub">扫码</span><strong>{stats.views}</strong></div><div className="stat"><span className="sub">生成</span><strong>{stats.generations}</strong></div><div className="stat"><span className="sub">复制</span><strong>{stats.copies}</strong></div></div></div></div>
}

function Records(){const [date,setDate]=useState("");const [query,setQuery]=useState("");const [records,setRecords]=useState<GenerationRecord[]>([]);useEffect(()=>{const controller=new AbortController();const timer=window.setTimeout(()=>{const params=new URLSearchParams();if(date)params.set("date",date);if(query.trim())params.set("q",query.trim());fetch(`/api/admin/records?${params}`,{cache:"no-store",signal:controller.signal}).then((response)=>response.json()).then((data)=>setRecords(data.records||[])).catch(()=>{})},200);return()=>{window.clearTimeout(timer);controller.abort()}},[date,query]);return <div className="card"><div className="section-title"><div><h2>生成记录</h2><p className="sub">可按日期、门店、项目和渠道筛选</p></div></div><div className="admin-grid"><label className="field">日期<input type="date" className="input" value={date} onChange={(event)=>setDate(event.target.value)}/></label><label className="field">关键词<input className="input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="门店、项目或渠道"/></label></div>{records.length===0?<div className="empty"><strong>暂无符合条件的生成记录</strong><p className="sub">顾客完成生成后，记录会显示在这里。不会收集姓名、病历或平台账号密码。</p></div>:<div className="record-list">{records.map((record)=><article className="history-card" key={record.id}><div className="history-meta"><span>{new Date(record.createdAt).toLocaleString("zh-CN")}</span><span>{record.style}</span></div><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:10}}><span className="badge">{record.storeName}</span><span className="badge">{record.projectName}</span>{record.channelId&&<span className="badge">{record.channelId}</span>}</div><p className="sub" style={{display:"-webkit-box",WebkitLineClamp:2,WebkitBoxOrient:"vertical",overflow:"hidden"}}>{record.content}</p></article>)}</div>}</div>}
